src/qtism/data/storage/xml/marshalling/TextRunMarshaller.php
This typo prevents marshall/unmarshalling functionality to work
=> Fix class name typo at TextRunMarshaller.php

qtism/runtime/tests/AssessmentTestSession.php
Without this patch it is impossible to resume a suspended session. The `isRunning()` method considers the session is running when the state is different from INITIAL or CLOSED. So a suspended session is never considered as not running, and cannot be resumed.
=> AssessmentTestSession: fix condition to resume a session

composer.json, qtism/common/utils/Format.php, test/qtism/common/utils/FormatTest.php
@bugalot @llecaque 
This changes prevents failing delivery compilation with not so nice, but still standard class names separated with more that one space.
=> Improved class detection compatibility with WC3 standard

composer.json, qtism/data/content/interactions/GapText.php, qtism/data/storage/xml/marshalling/GapChoiceMarshaller.php, test/qtism/data/storage/xml/XmlAssessmentItemDocumentTest.php, test/qtism/data/storage/xml/marshalling/GapMatchInteractionMarshallerTest.php, test/qtism/data/storage/xml/marshalling/GapTextMarshallerTest.php, test/samples/custom/items/rich_gap_text.xml
This is to implement https://oat-sa.atlassian.net/browse/TAO-4554
Unit test **testUnmarshallInvalid** in **test/qtism/data/storage/xml/marshalling/GapTextMarshallerTest.php** is still failing. I don't know if it should be removed?
=> GapText is now a flowStaticCollection to allow Math content

composer.json, qtism/runtime/expressions/OutcomeMaximumProcessor.php, qtism/runtime/expressions/OutcomeMinimumProcessor.php
This fixes the calculation of the sum of outcome maximum processing.
With this fix, only the items having the same weight identifier used in the outcome rule will have its weight taken into account. Before the fix, the same weight is applied to all items. (code greatly inspired from TestVariablesProcessor which works well)
I have a test sample (the one with the weight) that can be used to test this behaviour, in the JIRA https://oat-sa.atlassian.net/browse/TAO-4687
=> fixed the individual item weight

composer.json
Fix PHPUnit in require-dev following a warning message from packagist (composer 2 support)
=> updating upper case phpunit require-dev for composer 2.

src/qtism/runtime/tests/AssessmentItemSession.php, test/qtismtest/runtime/tests/AssessmentTestSessionTest.php, test/samples/custom/runtime/skipping/skipping.xml
This PR aims at making items without interactions (a.k.a. informational items) always "skippable", as no "non-default" values can be provided as a response to such items.
=> Skpping should be allowed for any item having no resps. decl.

src/qtism/runtime/storage/binary/AbstractQtiBinaryStorage.php
This PR aims at providing the QTI Binary Storage format with a version number. This will enable us to extend the QTI Binary Storage in the future, if required.
=> Add version to QTI Binary Storage.

src/qtism/data/results/Context.php, src/qtism/data/results/DuplicateSourceIdException.php, test/qtismtest/data/results/ContextTest.php
This PR is a follow-up to the https://github.com/oat-sa/qti-sdk/pull/157, adding a check for `sourceId` unicity.
If asked to add a new session identifier with an already existing `sourceId`, a `DuplicateSourceIdException` is thrown.
=> Added unique sourceId assertion.

src/qtism/data/QtiComponentCollection.php, src/qtism/data/results/Context.php, src/qtism/data/results/DuplicateSourceIdException.php, src/qtism/data/results/SessionIdentifierCollection.php, test/qtismtest/data/results/ContextTest.php
This PR allows adding one or more session identifier(s) built from two parameters:
- `sourceId`: a unique URI identifying the application which is adding the sessionIdentifier.
- `identifier`: a normalized string in the sense of https://www.w3.org/TR/xmlschema-2/#normalizedString, with a constraint of `whiteSpace` as `replace` (see https://www.w3.org/TR/xmlschema-2/#rf-whiteSpace for more details).
The unicity of the `sourceId` parameter is checked and a `DuplicateSourceIdException` is thrown when asked to add a new session identifier with an already existing `sourceId`.
A utility to normalize strings has been added in `qtism\common\datatypes\Utils::normalizeString` (tested with multi-bytes string, utf-8 and non-utf-8).
=> Merging to master for release 12.2.0

.travis.yml, src/qtism/data/content/interactions/GraphicOrderInteraction.php, src/qtism/data/content/interactions/OrderInteraction.php, src/qtism/data/storage/xml/marshalling/Marshaller.php, src/qtism/runtime/pci/json/Marshaller.php
PHP 7.4 has been released one month and a half ago and we had a couple breaking tests:
- Code in the form of `a ? b : c ? d : e` without proper parentheses is deprecated and will break in the next version of PHP
- accessing `null` as an array does not return `null` any more, `?? null` was added in json marshaller.
=> Added php 7.4 to travis.

qtism/data/state/ExternalScored.php, qtism/data/state/OutcomeDeclaration.php, qtism/data/storage/xml/marshalling/OutcomeDeclarationMarshaller.php, qtism/runtime/tests/AssessmentItemSession.php, test/qtism/data/state/OutcomeDeclarationTest.php
This PR adds externalScore checking methods, to avoid disclosing enumeration constants to SDK users.
=> Added externalScored checking methods.

src/qtism/data/state/ExternalScored.php, src/qtism/data/state/OutcomeDeclaration.php, src/qtism/data/storage/xml/marshalling/OutcomeDeclarationMarshaller.php, src/qtism/runtime/tests/AssessmentItemSession.php, test/qtismtest/data/state/OutcomeDeclarationTest.php, test/qtismtest/data/storage/xml/marshalling/OutcomeDeclarationMarshallerTest.php
ExternalScored attribute is a QTI 2.2 feature. It must not be taken in account in previous versions.
This PR also adds externalScore checking methods, to avoid disclosing enumeration constants to SDK users.
=> Added version check for externalScored management.

src/qtism/data/storage/xml/marshalling/ValueMarshaller.php, test/qtismtest/data/storage/xml/marshalling/ValueMarshallerTest.php
https://oat-sa.atlassian.net/browse/MS-90
You can test it with the following code snippet:
```
<?php
use qtism\data\storage\xml\XmlResultDocument;
require_once __DIR__ . '/vendor/autoload.php';
$xmlDocument = new XmlResultDocument();
$xml = <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<assessmentResult xmlns="http://www.imsglobal.org/xsd/imsqti_result_v2p1">
<context sourcedId="i5e4195ae583c374de82f78712be21a"/>
<itemResult identifier="item-1" datestamp="2020-02-11T09:12:15.703" sessionStatus="final">
<responseVariable identifier="RESPONSE" cardinality="multiple" baseType="identifier">
<candidateResponse>
<value><![CDATA[]]></value>
</candidateResponse>
</responseVariable>
</itemResult>
</assessmentResult>
XML;
$xmlDocument->loadFromString($xml);
```
=> Allow string baseType with null value

qtism/common/datatypes/QtiCoords.php, test/qtismtest/common/datatypes/CoordsTest.php
Backport of https://github.com/oat-sa/qti-sdk/pull/180 to legacy branch.
This PR fixes the detection of intersection of shapes by adding the counting of intersections between a horizontal line from a selected point and a polygon's edge between its first and last vertices.
=> Fix/udi 26/polygon intersection

composer.json
This PR removes the version tag in composer.json. It was overriding the actual release tag and prevented packagist to find out the releases.
=> Removed version tag in composer.json, locking tags on packagist.

qtism/data/rules/SetOutcomeValue.php
In a previous commit (https://github.com/oat-sa/qti-sdk/commit/41e0b29ab0a2c7284c56d44d1847e0d0ee7f050d#diff-89ab65b95ada3a7351e8ce3a05bf11e8L50), this constant was removed, because it was accessed in the same class by the getQtiClassName only, allowing undisclosed constant to external usages.
In fact, it was also accessed directly by Tao \ImportService\ to select QTI components with the `QtiComponents::getComponentsByClassName` method.
Every other calls to `QtiComponents::getComponentsByClassName` are using hard-coded strings, which is even worse.
Another way of selecting elements must be found.
=> Re-introduced CLASS_NAME constant which is accessed by TaoQtiItem ImportService

src/qtism/runtime/storage/binary/AbstractQtiBinaryStorage.php, src/qtism/runtime/storage/binary/QtiBinaryVersion.php, test/qtismtest/runtime/storage/binary/QtiBinaryVersionTest.php
This PR sets up a versioning for test session binary storage compatible with legacy branch, so that we can discriminate between master and legacy logic in retrieving test session.
A letter `M` for master and `L` for legacy is added after the version number, starting from version 10.
All versions below 10 are considered legacy version.
Also, detection of version by feature name is more readable.
=> Used legacy-compatible numbering for test session binary storage and added branch after version number.

src/qtism/runtime/common/Variable.php, test/qtismtest/runtime/common/ResponseVariableTest.php
Added tests for single cardinality on non-scalar values and multiple cardinality.
This helped figure out what the return value for non scalar datatypes should be: QtiDatatype for multiple cardinality, not an attempt to create a scalar value from non-scalar (for example, QtiPair must be returned, not a conversion of the QTiPair to string
Fixed the value returned in getDataModelValue.
=> Fixed non scalar data model values for multiple cardinality.

test/qtismtest/data/storage/xml/XmlDocumentTest.php
Travis has a version of libxml that delivers another message than the one developers have on their machine, creating one single failing test when running locally and not anyone in Travis.
This PR adds the local message to the test to avoid this burden.
=> Fixed test with two different messages.

src/qtism/data/storage/xml/marshalling/PromptMarshaller.php, test/qtismtest/data/storage/xml/marshalling/PromptMarshallerTest.php
Anchors are allowed in <prompt> QTI element from QTI 2.2.
This PR allows the use of links in interaction prompts for QTI 2.2 and later.
=> Allowed <a> in prompt for QTI 2.2.

composer.json, qtism/data/storage/xml/XmlDocument.php
Backport of https://github.com/oat-sa/qti-sdk/pull/211 to legacy
=> Allowed parsing of xml text node bigger than 10 mb.

qtism/common/datatypes/QtiCoords.php, test/qtismtest/common/datatypes/CoordsTest.php
__task:__ https://oat-sa.atlassian.net/browse/TAO-9725
__description:__ Actual correct response area is not ellipse in Graphic Select Point Interaction when ellipse selected
=> Actual correct response area is not ellipse in Graphic Select Point Interaction when ellipse selected

src/qtism/runtime/common/Variable.php, test/qtismtest/runtime/common/ResponseVariableTest.php
Related to: https://oat-sa.atlassian.net/browse/NEX-1753
`AbstractResultBuilder::buildVariables()` fails if QitFile is provided.
=> avoid exception if QtiFile is provided

src/qtism/data/content/interactions/ExtendedTextInteraction.php, src/qtism/data/content/interactions/TextEntryInteraction.php, test/qtismtest/data/content/interactions/ExtendedTextInteractionTest.php, test/qtismtest/data/content/interactions/TextInteractionTest.php
This PR aims at fixing the implementation of expectedLength for (Extended)TextEntryInteraction.
It allows 0 as a valid length and replace the usage of -1 as a magical value representing no value at all with a null value.
Related ticket:
https://oat-sa.atlassian.net/browse/NEX-1852
=> Allowed 0 as an expectedLength value.

src/qtism/data/content/interactions/ExtendedTextInteraction.php, test/qtismtest/data/content/interactions/ExtendedTextInteractionTest.php
As previous, the expectedLines also can accept 0 as a valid value.
=> Allowed 0 as an expectedLines value for textEntry interactions.

qtism/data/content/interactions/ExtendedTextInteraction.php, qtism/data/content/interactions/TextEntryInteraction.php, test/qtismtest/data/content/interactions/ExtendedTextInteractionTest.php, test/qtismtest/data/content/interactions/TextInteractionTest.php
This is the legacy backport of 
https://github.com/oat-sa/qti-sdk/pull/221
https://github.com/oat-sa/qti-sdk/pull/223
https://github.com/oat-sa/qti-sdk/pull/224
https://github.com/oat-sa/qti-sdk/pull/226
=> Allowed 0 as an accepted value for expectedLength and expectedLines in text interactions.

src/qtism/data/storage/xml/XmlDocument.php
Pull request summary
Related to : https://oat-sa.atlassian.net/browse/UNO-628
added LIBXML_BIGLINES | LIBXML_PARSEHUGE to work with big files, or data stored as a base64
=> added LIBXML_BIGLINES | LIBXML_PARSEHUGE to work with big files

qtism/data/storage/xml/XmlDocument.php
This PR allows XML parser to deal line numbers over 65535.
=> Added LIBXML_BIGLINES flag to allow to deal with long XML lines.

composer.json, qtism/common/datatypes/files/FileHash.php, qtism/runtime/pci/json/Marshaller.php, qtism/runtime/pci/json/Unmarshaller.php, qtism/runtime/storage/binary/QtiBinaryStreamAccess.php, test/qtismtest/runtime/pci/json/JsonMarshallerTest.php, test/qtismtest/runtime/pci/json/JsonUnmarshallerTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryStreamAccessTest.php
This is the legacy counterpart of https://github.com/oat-sa/qti-sdk/pull/227.
This PR aims at allowing the storage of a hash of an uploaded file instead of the content of the file itself, to avoid huge payloads to be stored in the test session. This requires that the file has been persisted to an external storage prior to call to qtism\runtime\pci\json\Unmarshaller::unmarshall.
A convenience to trigger this process is to use the FileHash::FILE_HASH_KEY constant as a key when encoding the JSON payload. An extra 4th parameter id is then required, containing the id of the persisted file allowing the retrieval of the file by the application that persisted the file on the external storage:
Replace key file in
{ "base" : { "file" : {
"mime" : "text-plain", 
"data" : "The contents of the …
=> Added storage of file hash instead of file content in the test session.

composer.json, src/qtism/runtime/expressions/operators/custom/CsvToContainer.php, src/qtism/runtime/expressions/operators/custom/CsvToMultiple.php, src/qtism/runtime/expressions/operators/custom/CsvToOrdered.php, src/qtism/runtime/expressions/operators/custom/math/fraction/Denominator.php, src/qtism/runtime/expressions/operators/custom/math/fraction/Numerator.php, src/qtism/runtime/expressions/operators/custom/math/fraction/NumeratorDenominator.php, src/qtism/runtime/expressions/operators/custom/math/graph/CountPointsThatSatisfyEquation.php, src/qtism/runtime/expressions/operators/custom/text/StringToNumber.php, test/qtismtest/runtime/expressions/operators/custom/CsvToMultipleTest.php, test/qtismtest/runtime/expressions/operators/custom/CsvToOrderedTest.php, test/qtismtest/runtime/expressions/operators/custom/math/fraction/DenominatorTest.php, test/qtismtest/runtime/expressions/operators/custom/math/fraction/NumeratorTest.php, test/qtismtest/runtime/expressions/operators/custom/math/graph/CountPointsThatSatisfyEquationTest.php, test/qtismtest/runtime/expressions/operators/custom/text/StringToNumberTest.php
QTI extension for custom operators were located in lib-tao-qti, that includes this repository for Tao inclusion.
Moving these operators makes them available for main branch also.
=> Moved custom operators from lib-qti-sdk.

.travis.yml, composer.json, qtism/runtime/expressions/operators/custom/CsvToContainer.php, qtism/runtime/expressions/operators/custom/CsvToMultiple.php, qtism/runtime/expressions/operators/custom/CsvToOrdered.php, qtism/runtime/expressions/operators/custom/math/fraction/Denominator.php, qtism/runtime/expressions/operators/custom/math/fraction/Numerator.php, qtism/runtime/expressions/operators/custom/math/fraction/NumeratorDenominator.php, qtism/runtime/expressions/operators/custom/math/graph/CountPointsThatSatisfyEquation.php, qtism/runtime/expressions/operators/custom/text/StringToNumber.php, test/qtismtest/runtime/expressions/operators/custom/CsvToMultipleTest.php, test/qtismtest/runtime/expressions/operators/custom/CsvToOrderedTest.php, test/qtismtest/runtime/expressions/operators/custom/math/fraction/DenominatorTest.php, test/qtismtest/runtime/expressions/operators/custom/math/fraction/NumeratorTest.php, test/qtismtest/runtime/expressions/operators/custom/math/graph/CountPointsThatSatisfyEquationTest.php, test/qtismtest/runtime/expressions/operators/custom/text/StringToNumberTest.php, travis-cfg.ini
This PR is the counterpart of https://github.com/oat-sa/qti-sdk/pull/238.
Code for support of QTI extension for custom operators is located in lib-tao-qti. That repository is used to include the legacy branch of oat-sa/qti-sdk in Tao software. The QTI extension is therefore not available for users of the main branch of qti-sdk.
This PR moves QTI extension for custom operators from lib-tao-qti to qti-sdk in the legacy branch.
=> Moved custom operators from lib-tao-qti.

qtism/runtime/storage/binary/QtiBinaryStreamAccess.php, qtism/runtime/storage/binary/QtiBinaryVersion.php, test/qtismtest/runtime/storage/binary/QtiBinaryStreamAccessTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryVersionTest.php
Count of variable declarations is stored in the test session using a short integer (0-255). This PR replaces this storage format with an integer (0-2147483647) and creates a new binary storage version, allowing the handling of test sessions with more than 255 variable declarations.
BEWARE:
All previously existing binary sessions are read correctly and subsequently written in this new format upon persistence.
BUT THERE'S NO TURNING BACK: A session stored in the new version won't be read correctly by a previous version, making the test unusable.
=> Added binary session version to store variable count as integer (over 255 variables).

qtism/data/expressions/operators/Match.php, test/qtismtest/data/expressions/operators/MatchTest.php
In PHP 8.*, `match` is a reserved word, the Match operator class has been renamed `MatchOperator` but former Tao compiled tests still contain generated PHP code with references to the `Match` class.
This PR makes sure these compiled tests still run in PHP 7.*.
However, when run on PHP 8.0, the older compiled tests containing usages of the `Match` class will have to be updated either by re-publishing or by running a script to update the generated PHP code.
=> Added compatibility pack for Match operator in PHP 7.*.

qtism/common/utils/Format.php, test/qtismtest/data/content/BodyElementTest.php
QTI class validation is producing thousands of steps due to under-optimized regex, making PHP give up at one moment. Just changed the regex to a simpler one.
=> Changed regex for QTI class producing too many steps.

src/qtism/common/utils/Format.php, test/qtismtest/data/content/BodyElementTest.php
QTI class validation is producing thousands of steps due to under-optimized regex, making PHP give up at one moment. Just changed the regex to a simpler one.
=> Changed regex for QTI class producing too many steps. - Main branch

qtism/data/content/interactions/HottextInteraction.php, qtism/data/content/interactions/PositionObjectInteraction.php, test/qtismtest/data/content/interactions/HottextInteractionTest.php, test/qtismtest/data/content/interactions/PositionObjectInteractionTest.php
In HottextInteraction, minChoices is valid when greater than maxChoices when the latter is 0.
=> Made HottextInteraction minChoices > 0 valid when maxChoices is 0.

src/qtism/data/content/interactions/HottextInteraction.php, src/qtism/data/content/interactions/PositionObjectInteraction.php, test/qtismtest/data/content/interactions/HottextInteractionTest.php, test/qtismtest/data/content/interactions/PositionObjectInteractionTest.php
In HottextInteraction and PositionObjectInteraction, minChoices is valid when greater than maxChoices when the latter is 0.
=> Made minChoices > maxChoices valid when maxChoices is 0 in HotTextInteraction and PositionObjectInteraction.

qtism/data/content/interactions/HottextInteraction.php, qtism/data/content/interactions/PositionObjectInteraction.php, test/qtismtest/data/content/interactions/HottextInteractionTest.php, test/qtismtest/data/content/interactions/PositionObjectInteractionTest.php
Made minChoices > maxChoices valid when maxChoices is 0 in HotTextInteraction and PositionObjectInteraction.
=> Merge for backport release 0.22.6

qtism/runtime/expressions/operators/Utils.php, test/qtismtest/runtime/expressions/operators/OperatorsUtilsTest.php, test/qtismtest/runtime/expressions/operators/PatternMatchProcessorTest.php
Avoided escaping caret when used as excluding character range marker.
=> Avoided escaping caret when used as excluding character range marker.

src/qtism/runtime/common/Variable.php, test/qtismtest/runtime/common/ResponseVariableTest.php
Response variable now supports value retrieval for result building with cardinality `Record`.
=> Added support for cardinality Record on ResponseVariable value conversion

qtism/common/utils/Format.php, qtism/data/content/xhtml/ObjectElement.php, qtism/data/storage/xml/marshalling/ObjectMarshaller.php, test/qtismtest/common/utils/FormatTest.php, test/qtismtest/data/content/xhtml/ObjectTest.php, test/qtismtest/data/storage/xml/marshalling/ObjectMarshallerTest.php
In order to fix this: https://oat-sa.atlassian.net/browse/AUT-245
**Issue:**
When fetching an QTI xml with object with dimensions set in percent like `<object width="100%" ...`
object fulfilled with integer width equals 100 because of type conversion
**Note:** this fix implementation reasonable in terms of legacy version. To satisfy a best practices rather to avoid mixed type for width and height attributes and using -1 as default. Use nullable string instead.
=> Fix object unmarshaller support for height and width in percent

src/qtism/data/content/BodyElement.php, test/qtismtest/data/content/BodyElementTest.php
[TR-1225](https://oat-sa.atlassian.net/browse/TR-1225)
The goal of this PR is to allow to set a class name of body element ending with space (trimed later)
=> fix: allow class names with spaces for body element marshalling

src/qtism/common/utils/Format.php, src/qtism/data/content/xhtml/Img.php, src/qtism/data/content/xhtml/ObjectElement.php, src/qtism/data/storage/xml/marshalling/ImgMarshaller.php, src/qtism/data/storage/xml/marshalling/ObjectMarshaller.php, test/qtismtest/common/utils/FormatTest.php, test/qtismtest/data/content/xhtml/ImgTest.php, test/qtismtest/data/content/xhtml/ObjectTest.php, test/qtismtest/data/storage/php/PhpDocumentTest.php, test/qtismtest/data/storage/xml/marshalling/ImgMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/MediaInteractionMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/ObjectMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/PositionObjectInteractionMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/PositionObjectStageMarshallerTest.php, test/samples/rendering/drawinginteraction_2.xml
This PR fixes support for `%` sign in height and width attributes of `<object>` and `<img>` QTI/HTML elements.
=> Support for % sign in width and height attributes of <img> and <object> tag - Main branch

src/qtism/runtime/common/VariableFactory.php, src/qtism/runtime/common/VariableFactoryInterface.php, src/qtism/runtime/storage/binary/LocalQtiBinaryStorage.php, src/qtism/runtime/storage/binary/QtiBinaryStreamAccess.php, test/qtismtest/runtime/common/VariableFactoryTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryStreamAccessTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryVersionTest.php
- feat: introduce `VariableFactoryInterface` and its implementation, allowing to instantiate any `Variable` from its `VariableDeclaration
- fix: skip redundant `Variable` instantiation and initialization upon `QtiBinaryStreamAccess::readAssessmentItemSession()` execution, and read the variable directly from the session state
This is not a _major_ improvement, but those variable's objects instantiation and initialization does take some time indeed, and I cannot call that time insignificant (around 10% of the `move` action request processing).
Perhaps, further improvement is possible, involving lazy initialization of the variable's internals.
Legacy release backport is #276.
=> Fix TR-1084: skip unnecessary variable instantiation

qtism/runtime/common/VariableFactory.php, qtism/runtime/common/VariableFactoryInterface.php, qtism/runtime/storage/binary/QtiBinaryStreamAccess.php, qtism/runtime/storage/binary/TemporaryQtiBinaryStorage.php, test/qtismtest/runtime/common/VariableFactoryTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryStreamAccessTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryVersionTest.php
- feat: introduce `VariableFactoryInterface` and its implementation, allowing to instantiate any `Variable` from its `VariableDeclaration
- fix: skip redundant `Variable` instantiation and initialization upon `QtiBinaryStreamAccess::readAssessmentItemSession()` execution, and read the variable directly from the session state
This backports #274.
=> Backport TR-1084: skip unnecessary variable instnatiatio

qtism/data/content/BodyElement.php, test/qtismtest/data/content/BodyElementTest.php
Backport of https://github.com/oat-sa/qti-sdk/pull/273 to legacy branch.
=> fix: allow class names with spaces for body element marshalling.

.gitignore, qtism/runtime/tests/AbstractSessionManager.php, test/qtismtest/runtime/tests/AssessmentTestSessionPreConditionsTest.php, test/samples/custom/runtime/preconditions/preconditions_sections_level_linear.xml
This PR appears in the context of resolving AUT-753, TR-1607, TR-1605 and TR-1606. It seems this bug fix will solve them all in a row :crossed_fingers: !
Long story short, the `preConditions`, to whatever they were bound to (`assessmentSection` or `assessmentItemRef`), were always behaving being bound to an `assessentItemRef`. As a result, a `preCondition` returning true, bound to an `assessmentSection` was leading to always behave as it was bound to the first `assessmentItemRef` of the `assessmentSection`.
This is now solved at the `assessmentTestSession` instantiation level, where the `preConditions` are applied to all `routeItems` that are children to the `sectionPart` (parent class of `assessmentSection` and `assessmentItemRef`) the `preCondition` belong to.
Enjoy :sweat_smile:  ! …
=> Fix/tr 1605/preconditions assessmentsection level

src/qtism/data/storage/xml/Utils.php, test/qtismtest/data/storage/xml/marshalling/TemplateDeclarationMarshallerTest.php
- fix: use array element addition operand instead of calling `array_push()` function within `qtism\data\storage\xml\Utils` methods
- chore: merge multiple `str_replace()` invocations into a single one in `qtism\data\storage\xml\Utils::escapeXmlSpecialChars()`
- chore: split `qtism\data\storage\xml\Utils::escapeXmlSpecialChars()` workflows
- fix: XML-encode a value before inserting it into DOM
This is an alternative solution to #291
_Legacy_ counterpart – #294
- author a test with Extended text interaction
- publish the test and launch the delivery as a test taker
- answer extended text interaction item with content containing non breaking spaces ` `, finish the test
- verify that result extraction consumer processed results without failure
=> Fix TR-1412 XML-encode values

qtism/data/storage/xml/Utils.php, test/qtismtest/data/storage/xml/marshalling/TemplateDeclarationMarshallerTest.php
- fix: use array element addition operand instead of calling `array_push()` function within `qtism\data\storage\xml\Utils` methods
- fix: XML-encode a value before inserting it into DOM
This is a _legacy_ counterpart to #293
- author a test with Extended text interaction
- publish the test and launch the delivery as a test taker
- answer extended text interaction item with content containing non breaking spaces ` `, finish the test
- verify that result extraction consumer processed results without failure
=> Fix TR-1412 XML-encode values – CG

src/qtism/runtime/tests/AssessmentTestSession.php, test/qtismtest/runtime/tests/AssessmentTestSessionTest.php
[TR-1264](https://oat-sa.atlassian.net/browse/TR-1264)
Allow jump navigation on test session for linear tests when manually set
=> feat: allow item jump on linear test when manually set

src/qtism/runtime/expressions/operators/Utils.php, test/qtismtest/runtime/expressions/operators/OperatorsUtilsTest.php
https://oat-sa.atlassian.net/browse/TR-3373
What is it about?
ExtendedText or InlineText with pattern: submit fails if validateResponses is set
1. Create item with constraint (pattern) or max words or max length
2. In test set "Validate Response"
3. Check test is working correct (in wrong variant it gives 500)
No dependencies
TODO
=> fix: remove checking caret & dollar, add test

qtism/runtime/expressions/operators/Utils.php, test/qtismtest/runtime/expressions/operators/OperatorsUtilsTest.php, test/qtismtest/runtime/expressions/operators/PatternMatchProcessorTest.php
https://oat-sa.atlassian.net/browse/TR-3373
What is it about?
ExtendedText or InlineText with pattern: submit fails if validateResponses is set
1. already tested
No dependencies
TODO
=> fix/tr-3373: update removing caret and dollar, update tests

src/qtism/runtime/tests/BasicSelection.php, test/qtismtest/runtime/tests/BasicSelectionTest.php, test/samples/custom/runtime/selection_ordering/selection_and_ordering.xml
Fixed and issue with item/section selection algorithm. Whenever required and non-required are in the route, the selection would go wrong and required item got selected several times.
Related to : https://oat-sa.atlassian.net/browse/TR-3645
- take a test attached to the linked ticket
- make sure that the execution does not freeze during the test and can be completed, 5 items are presented
Companion legacy PR :
=> fix: selection of required and not required items

qtism/runtime/tests/BasicSelection.php, test/qtismtest/runtime/tests/BasicSelectionTest.php, test/samples/custom/runtime/selection_ordering/selection_and_ordering.xml
Same changes as in https://github.com/oat-sa/qti-sdk/pull/308
=> legacy fix: selection of required and not required items

src/qtism/runtime/expressions/operators/Utils.php, src/qtism/runtime/tests/Utils.php, test/qtismtest/runtime/expressions/operators/OperatorsUtilsTest.php, test/qtismtest/runtime/tests/TestUtilsTest.php
This bug occurs when an TextEntry interaction is authored with a maximum length, resulting in the `patternMask` attribute being a regex `^[\\s\\S]{0,N}$` used for input length validation. Today, that validation is applied differently on backend and Solar frontend, which [parses](https://github.com/oat-sa/tao-deliver-fe/blob/develop/packages/item-runner/src/runner/util/patternMask.js#L31) the `maxlength` number back out of the pattern in order to check the input's length does not exceed it.
This is significant on Unicode inputs (see [byte counter](https://mothereff.in/byte-counter)):
- `a` // JS string length = 1; bytes = 1; patternMask `{0,1}` = valid
- `å` // JS string length = 1; bytes = 2; patternMask `{0,1}` = invalid
- `😊` // JS string length = 1; bytes = 4; patternMask `{0,1}` = …
=> Fix/tr 4332/patternmask length validation

qtism/data/content/BodyElement.php, qtism/data/storage/xml/marshalling/Marshaller.php, qtism/data/storage/xml/marshalling/RecursiveMarshaller.php, test/qtismtest/data/content/BodyElementTest.php
https://oat-sa.atlassian.net/browse/AUT-2337
Import/export shared stimulus and keep the "lang" and "dir" attributes is not working.
Example where the problem happens: https://github.com/oat-sa/extension-tao-mediamanager/blob/master/model/sharedStimulus/encoder/SharedStimulusMediaEncoder.php#L51 When we call XmlDocument::load() it does not keep the attributes we need. 
- Add possibilities for custom attributes in the BodyElement
- https://github.com/oat-sa/extension-tao-itemqti/pull/2162
- https://github.com/oat-sa/lib-tao-qti/pull/121
=> feat: allow custom attributes for BodyElement to support lang and dir

.github/workflows/continuous-integration.yaml, composer.json, qtism/common/dom/SerializableDomDocument.php, qtism/data/ExternalQtiComponent.php, qtism/data/IExternal.php, qtism/data/content/interactions/CustomInteraction.php, qtism/data/expressions/operators/CustomOperator.php, qtism/data/rules/Selection.php, test/qtismtest/common/dom/SerializableDomDocumentTest.php, test/qtismtest/data/content/MathTest.php, test/qtismtest/data/storage/xml/marshalling/MathMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/XIncludeMarshallerTest.php
1. BREAKING CHANGE: `SerializableDomDocument` no longer extends `DOMDocument` due to a serialization-preventing bug in PHP 8.1 https://github.com/php/php-src/issues/8996
2. Now where it possible  after call getXml() we should assign `ExternalQtiComponent`  as `SerializableDomDocument`  not like `DOMDocument`
3. Correct test to check right class type.
=> Feature TR-4391 ensure PHP 8.1 support by the legacy release

.github/workflows/continuous-integration.yaml, composer.json, src/qtism/common/dom/SerializableDomDocument.php, src/qtism/data/ExternalQtiComponent.php, src/qtism/data/IExternal.php, src/qtism/data/content/interactions/CustomInteraction.php, src/qtism/data/expressions/operators/CustomOperator.php, src/qtism/data/rules/Selection.php, test/qtismtest/common/dom/SerializableDomDocumentTest.php, test/qtismtest/data/content/MathTest.php, test/qtismtest/data/storage/xml/marshalling/MathMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/XIncludeMarshallerTest.php
1. BREAKING CHANGE: `SerializableDomDocument` no longer extends `DOMDocument` due to a serialization-preventing bug in PHP 8.1 https://github.com/php/php-src/issues/8996
2. BREAKING CHANGE:  Drop support for PHP <7.4
3. Now where it possible  after call getXml() we should assign `ExternalQtiComponent`  as `SerializableDomDocument`  not like `DOMDocument`
4. Correct test to check right class type.
=> Feature TR-4391 ensure PHP 8.1 support

.github/workflows/continuous-integration.yaml, composer.json, src/qtism/common/dom/SerializableDomDocument.php, src/qtism/data/ExternalQtiComponent.php, src/qtism/data/IExternal.php, src/qtism/data/content/interactions/CustomInteraction.php, src/qtism/data/expressions/operators/CustomOperator.php, src/qtism/data/rules/Selection.php, test/qtismtest/common/dom/SerializableDomDocumentTest.php, test/qtismtest/data/content/MathTest.php, test/qtismtest/data/storage/xml/marshalling/MathMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/XIncludeMarshallerTest.php
- Added support for PHP 8.1
- BREAKING CHANGE: `SerializableDomDocument` no longer extends `DOMDocument` due to a serialization-preventing bug in PHP 8.1 https://github.com/php/php-src/issues/8996
=> Release 17.0.0

src/qtism/data/storage/xml/Utils.php, test/qtismtest/data/storage/xml/XmlUtilsTest.php
Related to: https://oat-sa.atlassian.net/browse/TR-4212
To prevent XML validation errors, the XML attributes are escaped so that some entities are encoded (`"`, `&`, `<`, `>`). This is made implicitly by the PHP built-in engine, but it is also enforced by the [attribute setter](https://github.com/oat-sa/qti-sdk/blob/5119fc6c91e3e39c36a035eaef9ee840fb573320/src/qtism/data/storage/xml/Utils.php#L353). This results in double encoding. Unfortunately, it does not look like the unescape is applied properly while reading back the XML.
~~This code change adds decoding of the HTML special chars when reading attributes.~~
This code change removes the double encoding of attributes.
How to test:
- run the unit tests (`vendor/bin/phpunit`)
- check out the branch in a TAO instance (composer: …
=> Fix/TR-4212/Decode HTML entities in attributes

qtism/data/storage/xml/Utils.php, test/qtismtest/data/storage/xml/XmlUtilsTest.php
Related to: https://oat-sa.atlassian.net/browse/TR-4212
To prevent XML validation errors, the XML attributes are escaped so that some entities are encoded (`"`, `&`, `<`, `>`). This is made implicitly by the PHP built-in engine, but it is also enforced by the [attribute setter](https://github.com/oat-sa/qti-sdk/blob/5119fc6c91e3e39c36a035eaef9ee840fb573320/src/qtism/data/storage/xml/Utils.php#L353). This results in double encoding. Unfortunately, it does not look like the unescape is applied properly while reading back the XML.
~~This code change adds decoding of the HTML special chars when reading attributes.~~
This code change removes the double encoding of attributes.
How to test:
- run the unit tests (`vendor/bin/phpunit`)
- check out the branch in a TAO instance (composer: …
=> Fix/TR-4212/Legacy/Decode HTML entities in attributes

src/qtism/runtime/storage/binary/AbstractQtiBinaryStorage.php, src/qtism/runtime/tests/AssessmentTestSession.php
During creating DurationStore for Assessment Session we skip to add duration for AsessmentItem it happens because `$access`  follow to elements inside items not on its properties. 
1. Extend duration store with item limits data if it set for item. 
https://www.loom.com/share/f6d938a834754daeae6f83d884db6fb1
=> fix: Store Item Limits to DurationStore

src/qtism/data/content/xhtml/html5/Rb.php, src/qtism/data/content/xhtml/html5/Rp.php, src/qtism/data/content/xhtml/html5/Rt.php, src/qtism/data/content/xhtml/html5/Ruby.php, src/qtism/data/storage/xml/marshalling/ContentMarshaller.php, src/qtism/data/storage/xml/marshalling/Html5RbMarshaller.php, src/qtism/data/storage/xml/marshalling/Html5RpMarshaller.php, src/qtism/data/storage/xml/marshalling/Html5RtMarshaller.php, src/qtism/data/storage/xml/marshalling/Html5RubyMarshaller.php, src/qtism/data/storage/xml/marshalling/Qti22MarshallerFactory.php, src/qtism/runtime/rendering/markup/xhtml/RbRenderer.php, src/qtism/runtime/rendering/markup/xhtml/RpRenderer.php, src/qtism/runtime/rendering/markup/xhtml/RtRenderer.php, src/qtism/runtime/rendering/markup/xhtml/RubyRenderer.php, src/qtism/runtime/rendering/markup/xhtml/XhtmlRenderingEngine.php, test/qtismtest/data/content/xhtml/html5/RbTest.php, test/qtismtest/data/content/xhtml/html5/RpTest.php, test/qtismtest/data/content/xhtml/html5/RtTest.php, test/qtismtest/data/content/xhtml/html5/RubyTest.php, test/qtismtest/data/storage/xml/marshalling/Html5RbMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/Html5RpMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/Html5RtMarshallerTest.php, test/qtismtest/data/storage/xml/marshalling/Html5RubyMarshallerTest.php, test/qtismtest/runtime/expressions/VariableProcessorTest.php, test/samples/custom/items/2_2/ruby_html5.xml
Since Ruby tags are a standard HTML5 feature, they are natively [supported by all major web browsers](https://caniuse.com/?search=ruby). This means that manually adding Ruby to the QTI XML markup should already works out of the box in the Test Runner. However there seems to be a blocker in our package publication (QTI marshalling of HTML5 ruby tags) that prevents publishing a test that contains item(s) with Ruby markup.
Marshallers/unmarshallers for the following Ruby tags are added in QTI-SDK:
<ruby>
<rb>
<rt>
<rp>
Add tag description classes
Add new Marshaling 
Add new UnMarshaling 
Add test for cover new elements 
[JsonCompilation](https://github.com/oat-sa/lib-qti-item-json-compilation/pull/53)
[QTI-SDK-LEGACY](https://github.com/oat-sa/qti-sdk/pull/331) …
=> Add <ruby> tag to marshaling and unmarshaling

src/qtism/runtime/tests/AssessmentItemSession.php, src/qtism/runtime/tests/AssessmentTestSession.php, test/qtismtest/runtime/expressions/VariableProcessorTest.php, test/qtismtest/runtime/tests/AssessmentItemSessionTest.php
When user launches the test with "Validate responses" and “maximum duration” settings enabled for an item, reaches this item and wait until timer is out (no response provided/not valid response provided) - test fails with “500 error”. "Unexpected Error. Sorry, an unexpected error happened during the test. Please contact your test administrator" message is displayed to the user. Same for “Allow skipping“.
Test with enabled "Validate responses" and “maximum duration” settings is created and published (see attached file). 
Test with disabled "Allow skipping" and “maximum duration” settings is created and published
1. Launch the first test from the preconditions via [LTI 1.3 ](https://devkit-oat-dev.dev.gcp-eu.taocloud.org/platform/message/launch/lti-resource-link?registration=deliverRegistrat …
=> fix: allow to save event empty answer if timeout happens

src/qtism/runtime/tests/AssessmentItemSession.php
When user launches the test with "Validate responses" and “maximum duration” settings enabled for an item, reaches this item and wait until timer is out (no response provided/not valid response provided) - test fails with “500 error”. "Unexpected Error. Sorry, an unexpected error happened during the test. Please contact your test administrator" message is displayed to the user. Same for “Allow skipping“.
Test with enabled "Validate responses" and “maximum duration” settings is created and published (see attached file). 
Test with disabled "Allow skipping" and “maximum duration” settings is created and published
1. Launch the first test from the preconditions via [LTI 1.3 ](https://devkit-oat-dev.dev.gcp-eu.taocloud.org/platform/message/launch/lti-resource-link?registration=deliverRegistrat …
=> fix: provide new flag for skip validation with check on empty response

src/qtism/runtime/tests/AssessmentTestSession.php
If we timeout on last section in a test we see error 
1. launch test from Preconditions
2. navigate to the last Item of the last Section (items in front could be answered, or left unanswered)
3. wait until the last Section’s Timer expires
4. select Finish test in confirmation dialog
Validate route if move to next session is correct
If it is incorrect close test section 
https://user-images.githubusercontent.com/2750628/194335954-ea82c4ff-a00d-4954-aba8-6761585ff103.mov
=> Close test session next section to move invalid

codecov.yml, src/qtism/runtime/common/OutcomeVariable.php, src/qtism/runtime/common/Variable.php, src/qtism/runtime/storage/binary/QtiBinaryStreamAccess.php, src/qtism/runtime/storage/binary/QtiBinaryVersion.php, src/qtism/runtime/tests/AssessmentItemSession.php, test/qtismtest/runtime/common/OutcomeVariableTest.php, test/qtismtest/runtime/common/ResponseVariableTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryStreamAccessTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryVersionTest.php, test/qtismtest/runtime/tests/AssessmentItemSessionTest.php
https://user-images.githubusercontent.com/2943256/195177302-c34c72d9-fea9-47ab-8b1a-11b99759a637.mov
1. Have a non-linear navigation _readonly_ PCI-containing delivery execution (e.g. with a Text-Reader PCI)
2. Launch it as a non-anonymous user
3. Submit an item with the PCI
4. Close the delivery execution
5. Relaunch the same delivery execution as the same user again
6. Check the submitted item state, it should remain in the _completed_ state
[The fix is available on OAT dev](https://devkit-oat-dev.dev.gcp-eu.taocloud.org/platform/message/launch/lti-resource-link?registration=deliverRegistration&user_type=custom&user_list=c3po&custom_user_id=MODIFY_ME&launch_url=https://testrunner-oat-dev.dev.gcp-eu.taocloud.org/api/v1/auth/launch-lti-1p3/de3c99c941d9&claims=%7B%0D%0A%20%20%20%20%22https: …
=> Fix TR-4668 response variable default values completion status calculation

qtism/data/content/xhtml/html5/Figcaption.php, qtism/data/content/xhtml/html5/Figure.php, qtism/data/content/xhtml/html5/Rb.php, qtism/data/content/xhtml/html5/Rp.php, qtism/data/content/xhtml/html5/Rt.php, qtism/data/content/xhtml/html5/Ruby.php, qtism/data/storage/xml/marshalling/GapChoiceMarshaller.php
When we configure Ruby in Asset tab and add it to passage , we got error `InlineCollection objects only accept to store Inline objects` 
Include Ruby tags to Inline interfaces, also Include to that Group `Figure` because it should be same with `Img`
https://user-images.githubusercontent.com/2750628/200549592-b057cb06-97f7-4d68-9801-61e5bef1984e.mov
=> Legacy: Allow ruby tag be possible to add on InlineColletions

src/qtism/common/datatypes/files/FileManager.php, src/qtism/common/datatypes/files/FileSystemFileManager.php, src/qtism/runtime/pci/json/Marshaller.php, src/qtism/runtime/pci/json/Unmarshaller.php, src/qtism/runtime/storage/binary/QtiBinaryStreamAccess.php, test/qtismtest/common/datatypes/files/FileSystemFileManagerTest.php, test/qtismtest/runtime/pci/json/JsonMarshallerTest.php, test/qtismtest/runtime/pci/json/JsonUnmarshallerTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryStreamAccessTest.php
Name of original file lost on different steps of test session
- at persisting by file manager
- at persisting test session in binary stream
I have __doubts__ about implemented way of encoding file id with name in qti binary stream
required for - https://github.com/oat-sa/bundle-qti/pull/60
required for - https://github.com/oat-sa/tao-deliver-be/pull/1008
validate and adjust tests if necessary
=> Fix support of original file name

src/qtism/common/datatypes/files/FileManager.php, src/qtism/common/datatypes/files/FileSystemFileManager.php, src/qtism/runtime/pci/json/Marshaller.php, src/qtism/runtime/pci/json/Unmarshaller.php, src/qtism/runtime/storage/binary/QtiBinaryStreamAccess.php, test/qtismtest/common/datatypes/files/FileSystemFileManagerTest.php, test/qtismtest/runtime/pci/json/JsonMarshallerTest.php, test/qtismtest/runtime/pci/json/JsonUnmarshallerTest.php, test/qtismtest/runtime/storage/binary/QtiBinaryStreamAccessTest.php
release of https://github.com/oat-sa/qti-sdk/pull/347
=> Release 18.0.0

composer.json, src/qtism/data/storage/xml/XmlDocument.php, src/qtism/data/storage/xml/filesystem/FilesystemException.php, src/qtism/data/storage/xml/filesystem/FilesystemFactory.php, src/qtism/data/storage/xml/filesystem/FilesystemInterface.php, src/qtism/data/storage/xml/filesystem/FlysystemV1Filesystem.php, src/qtism/data/storage/xml/filesystem/FlysystemV2Filesystem.php, test/qtismtest/QtiSmTestCase.php
This PR adds support for abstracted filesystems instead of relying on Flysystem v1 exclusively.  This started as a need to support Flysystem v2+, but it was just as easy to move the Filesystem implementation in XmlDocument to interfaces in the event anybody else needs to provide their own read/write implementation.
There's an implementation of the new FilesystemInterface for Flysystemv1 and Flysystemv2+, and I've added backwards compatibility to assure XmlDocument::setFilesystem() still accepts v1 Filesystem classes directly.
=> Abstracted Filesystem Support

src/qtism/data/content/ItemBody.php, src/qtism/data/storage/xml/marshalling/Marshaller.php, test/qtismtest/data/storage/xml/XmlAssessmentTestDocumentTest.php, test/samples/custom/items/item_body_dir_attr.xml
support for RTL at the block or interaction level was dropped since MCA (who was the original sponsor for this) did not need to change the orientation within an item (what we called bidirectional content back then). So it stayed on the itemBody alone, as part of the dir attribute.
1. Use const for element name 
2. Include itemBody to white list of `dir` arttribute elements
=> feat: allow to use dir attr in itemBody element

composer.json
FIx Time-of-check Time-of-use (TOCTOU) Race Condition in league/flysystem
=> fix: use patched version for vulnerable league/flysystem repository

src/qtism/common/storage/BinaryStreamAccess.php, src/qtism/common/storage/UnpackingStreamException.php
this PR aim to add proper handling false result of `unpack` function and trigger exception, to avoid TypeError
```
2023-05-04T17:53:14+02:00 In BinaryStreamAccess.php line 164:
2023-05-04T17:53:14+02:00                                                                      
2023-05-04T17:53:14+02:00   current(): Argument #1 ($array) must be of type array, bool given  
2023-05-04T17:53:14+02:00 
```
=> Handle false result of unpack function at test session reading

src/qtism/common/storage/BinaryStreamAccess.php
use new exception driven tryUnpack at missed readInteger method
=> fix: use tryUnpack on readInteger

src/qtism/data/expressions/RandomFloat.php
This PR aims to fix PHP marshalling of `RandomFloat` component
=> fix: add missing bean property

src/qtism/runtime/tests/Utils.php
This PR aim to refactor max words validation. 
With this changes in case if we found in provided with interaction pattern corresponding to Authoring pattern 
we ignore pattern matching extract min and max restrictions split string by pattern `/[\s.,:;?!&#%\/*+=]+/` and count entries.
In case if pattern not corresponding to Authoring pattern system works as before and rely on provided pattern
- install branch
- launch delivery with extended text interaction with words restriction
- words count in content like `!word anotherWord word.with.dots!` should be counted more accurate as 5 entries
[TR-4540]: https://oat-sa.atlassian.net/browse/TR-4540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactoring of max word validation

src/qtism/data/rules/BranchRuleCollection.php, src/qtism/runtime/tests/AssessmentTestSession.php, src/qtism/runtime/tests/RouteItem.php, test/qtismtest/runtime/tests/AssessmentTestSessionBranchingsTest.php, test/samples/custom/runtime/branchings/branching_rules.xml
https://oat-sa.atlassian.net/browse/TR-5932
Make branch rules work again between test part with nonlinear navigation
- https://github.com/oat-sa/tao-deliver-be/pull/1252
=> Fix TR-5932 branching rules evaluation for non-linear test parts

src/qtism/data/rules/BranchRuleCollection.php, src/qtism/runtime/tests/AssessmentTestSession.php, src/qtism/runtime/tests/RouteItem.php, test/qtismtest/runtime/tests/AssessmentTestSessionBranchingsTest.php, test/samples/custom/runtime/branchings/branching_rules.xml
Release fix for https://oat-sa.atlassian.net/browse/TR-5932
=> Release 19.2.1

src/qtism/runtime/common/Variable.php
This PR skips extra variable conversion steps when generating a result
[PISA25-468]: https://oat-sa.atlassian.net/browse/PISA25-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: simplify result variable generation by skipping string-to-typed object conversion

.github/workflows/continuous-integration.yaml, src/qtism/data/content/interactions/ExtendedTextInteraction.php, src/qtism/data/state/ResponseValidityConstraint.php, test/qtismtest/data/content/interactions/ExtendedTextInteractionTest.php, test/qtismtest/data/state/ResponseValidityConstraintTest.php
https://oat-sa.atlassian.net/browse/TR-6169
Skip validation for size on XHTML text 
- https://github.com/oat-sa/tao-deliver-be/pull/1346
[TR-6169]: https://oat-sa.atlassian.net/browse/TR-6169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: not validate maxWords for XHTML extendTextInteractions

src/qtism/data/AssessmentItem.php, test/qtismtest/data/AssessmentItemTest.php
Allow using digits for item identifier
=> Feat/aut 3705/update item qti identifer

qtism/data/AssessmentItem.php, test/qtismtest/data/AssessmentItemTest.php
This allow to set identifier that is validated against normalized string
=> fix: AssessmentItem::setIdentifier uses isNormalizedString

src/qtism/data/storage/xml/Utils.php, test/qtismtest/data/storage/xml/XmlUtilsTest.php
This PR decoded special HTML symbols in responses before transforming them into XML object 
to avoid error 
```
SimpleXMLElement::__construct(): <value>160\u00b4\b<\/value>
```
These changes not been fully tested that's why it is a draft 
[TR-6347]: https://oat-sa.atlassian.net/browse/TR-6347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: response values encoding to support compatibility with XML when generating the results

src/qtism/runtime/common/Variable.php, test/qtismtest/runtime/common/ResponseVariableTest.php
This PR adds `fieldIdentifier` and `baseType` attributes to the `<value>` that is part of a record-typed `<candidateResponse>`
That's exactly what the 1EdTech specs prescribe to do [here](https://www.imsglobal.org/question/qtiv2p2p1/QTIv2p2-Results-InfoBindModelv1p0p1/imsqtiv2p2_result_v1p0_InfoBindv1p0p1.html#DerivedCharacteristic_Value.Attr_fieldIdentifier)
1. Complete a test with a `record`-typed response variable
2. Generate the results.xml
|Before|After|
|-|-|
|<img width="771" alt="image" src="https://github.com/user-attachments/assets/697d09b8-273b-4078-8746-469176e4e05c">|<img width="771" alt="image" src="https://github.com/user-attachments/assets/00c8f7c9-f0ba-488c-9cd3-e75a797e832f">|
[TR-5267]: https://oat-sa.atlassian.net/browse/TR-5267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> fix: add `fieldIdentifier` and `baseType` properties to the `Value` class when the value forms part of a record

.github/workflows/continuous-integration.yaml, src/qtism/runtime/expressions/operators/FieldValueProcessor.php, test/qtismtest/common/dom/SerializableDomDocumentTest.php, test/qtismtest/runtime/expressions/operators/FieldValueProcessorTest.php, test/qtismtest/runtime/processing/ResponseProcessingEngineTest.php
This PR makes `FieldValue` processor less strict, and resolve into a `null` value in case the referenced variable itself is a `null`.
e.g. the following rule will produce a `null` instead of failing with an exception if the `RESPONSE` variable is not set at all.
```xml
<fieldValue fieldIdentifier="result">
<variable identifier="RESPONSE"/>
</fieldValue>
```
In other words, instead of treating that expression as `RESPONSE.result`, we will treat it as `RESPONSE?.result`.
According to https://www.imsglobal.org/sites/default/files/spec/qti/v3/info/index.html#Data_FieldValue, the 
> The field value operator takes a sub-expression with a record container value. The result is the value of the field with the specified field-identifier. If there is no field with that identifier then the result of …
=> fix: null-safe dereferencing of record-typed variables fields via the `<fieldValue>` operand

src/qtism/cli/Render.php
It is there to fix a small problem, introduced in one of the previous PRs.
As per the customer report, it shows syntax errors when trying to run the command from the SDK readme:
```sh
./vendor/bin/qtisdk render -df --source /Users/*/Downloads/i6422d9afb42b32279aab31294164637a8/qti.xml --flavour goldilocks > ./qti.html
PHP Parse error:  syntax error, unexpected token "{" in /Users/*/Downloads/test/taoApi/vendor/qtism/qtism/src/qtism/cli/Render.php on line 283
```
Which is pretty logical, since variable interpolation won't work outside of "string context".
=> chore: fixing syntax throwing an error

src/qtism/data/ExtendedAssessmentItemRef.php, src/qtism/data/IAssessmentItem.php, src/qtism/data/rules/TemplateCondition.php, src/qtism/runtime/expressions/ExpressionEngine.php, src/qtism/runtime/pci/json/MarshallingException.php, src/qtism/runtime/pci/json/UnmarshallingException.php, src/qtism/runtime/rendering/markup/AbstractMarkupRenderer.php, src/qtism/runtime/rendering/markup/AbstractMarkupRenderingEngine.php, src/qtism/runtime/rendering/markup/xhtml/AbstractXhtmlRenderer.php, src/qtism/runtime/rendering/markup/xhtml/BodyElementRenderer.php, src/qtism/runtime/rendering/markup/xhtml/FeedbackBlockRenderer.php
Allow other Symfony versions 
[TR-6487]: https://oat-sa.atlassian.net/browse/TR-6487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: deprecation errors
