oat-sa/qti-sdk

qtism/runtime/tests/AssessmentTestSession.php

I need this to make my sample test work.
I took the fix form the master branch : https://github.com/oat-sa/qti-sdk/commit/b1f6502c8ac9771c42cb6054a25b15e906a00d2c
This is required for : https://oat-sa.atlassian.net/browse/TAO-858

add fix made on the master b1f6502c8ac9771c42cb6054a25b15e906a00d2c

---

composer.json
qtism/common/datatypes/Duration.php
qtism/runtime/tests/AssessmentItemSession.php
qtism/runtime/tests/AssessmentTestSession.php
test/QtiSmTestCase.php
test/qtism/common/datatypes/DurationTest.php
test/qtism/runtime/common/OutcomeVariableTest.php
test/qtism/runtime/common/RecordContainerTest.php
test/qtism/runtime/storage/binary/BinaryStreamAccessTest.php
test/qtism/runtime/storage/binary/TemporaryQtiBinaryStorageTest.php
test/qtism/runtime/storage/common/AssessmentTestSeekerTest.php
test/qtism/runtime/tests/AssessmentItemSessionTimingTest.php
test/qtism/runtime/tests/AssessmentTestSessionTest.php
test/qtism/runtime/tests/AssessmentTestSessionTimingTest.php

Partially related to this task https://oat-sa.atlassian.net/browse/TAO-1106
Added support of microseconds to durations

Microseconds

---

qtism/data/storage/xml/marshalling/AssessmentTestMarshaller.php

Pinging you, @bugalot , as can't assign directly

Marshalling sequence changed, in order to be compatibale with xsd schema

---

composer.json

rely on oatsa repo instead of Alroniks' one

Change dependencies

---

composer.json
qtism/common/datatypes/Duration.php
qtism/runtime/tests/AssessmentItemSession.php

**!Note** Not to merge before fixes in extensions

Fix rependency issue with dtms library

---

composer.json
qtism/runtime/expressions/MapResponseProcessor.php
test/qtism/runtime/expressions/MapResponseProcessorTest.php

Fixed https://oat-sa.atlassian.net/browse/TAO-4329

compare single mapping result to the lower and upper bound

---

test/qtismtest/runtime/expressions/operators/TruncateProcessorTest.php
test/qtismtest/runtime/processing/PrintedVariableEngineTest.php

[https://oat-sa.atlassian.net/browse/TAO-4295](https://oat-sa.atlassian.net/browse/TAO-4295)

Unit tests for TAO-4295

---

composer.json
qtism/common/utils/Format.php
qtism/common/utils/data/CharacterMap.php

As during serialization the identifiers get rechecked, there are millions of calls to this function, hence the regular expressions are becoming a performance bottleneck.

Use charactermap for quick id validation

---

src/qtism/runtime/tests/AssessmentTestSession.php
test/qtismtest/runtime/tests/AssessmentTestSessionConfigInitializationAllItemsTest.php

Related to: https://oat-sa.atlassian.net/browse/NEX-444
I added new config paramerter `INITIALIZE_ALL_ITEMS` which forces initialization of all items in `selectEligibleItems` method

added config parameter for AssessmentTestSession

---

.travis.yml
composer.json
phpunit.xml.dist
qtism/runtime/pci/json/Marshaller.php

Upper case is deprecated in composer package names.

Added travis tests for legacy branch

---

src/qtism/runtime/tests/AssessmentTestSession.php
test/qtismtest/runtime/tests/AssessmentTestSessionExitTest.php

[NEX-1589](https://oat-sa.atlassian.net/browse/NEX-1589)
On `moveNextTestPart` end the session if no more TestPart

end the test session when no more test part on move

---

test/qtismtest/runtime/tests/AssessmentTestSessionExitTest.php

Complementary PR to the previous one to have assertions for every case.

Added assertions to check that the testsession is closed on each test.

---

src/qtism/data/storage/xml/XmlDocument.php

https://oat-sa.atlassian.net/browse/NEX-1637

Added LIBXML_PARSEHUGE flag

---

test/qtismtest/data/content/interactions/ExtendedTextInteractionTest.php

Additional tests for ticket https://oat-sa.atlassian.net/browse/NEX-1852

Added missing tests expectedLength 0 and positive values.

---

.travis.yml
qtism/common/utils/Format.php
qtism/data/content/xhtml/Img.php
qtism/data/content/xhtml/ObjectElement.php
qtism/data/storage/xml/marshalling/ImgMarshaller.php
qtism/data/storage/xml/marshalling/ObjectMarshaller.php
test/qtismtest/common/utils/FormatTest.php
test/qtismtest/data/content/interactions/PositionObjectInteractionTest.php
test/qtismtest/data/content/xhtml/ImgTest.php
test/qtismtest/data/content/xhtml/ObjectTest.php
test/qtismtest/data/storage/php/PhpDocumentTest.php
test/qtismtest/data/storage/xml/marshalling/ImgMarshallerTest.php
test/qtismtest/data/storage/xml/marshalling/MediaInteractionMarshallerTest.php
test/qtismtest/data/storage/xml/marshalling/PositionObjectInteractionMarshallerTest.php
test/qtismtest/data/storage/xml/marshalling/PositionObjectStageMarshallerTest.php
test/samples/rendering/drawinginteraction_2.xml

Continuation of #269 extended to <img> element.

Support for % sign in width and height attributes of <img> tag.

---

.gitignore
src/qtism/runtime/processing/ResponseProcessingEngine.php
src/qtism/runtime/rules/ProcessingCollectionException.php
test/qtismtest/runtime/processing/ResponseProcessingEngineTest.php
test/qtismtest/runtime/tests/AssessmentTestSessionTest.php
test/samples/custom/runtime/incorrect_outcome_processing.xml

[TR-1260](https://oat-sa.atlassian.net/browse/TR-1260)
The goal of this PR is to ignore broken process rules to skip the erroneous outcome value generation but continue the remaining ones

feat: don't stop response processing on broken rule

---

qtism/runtime/tests/AssessmentTestSession.php
test/qtismtest/runtime/tests/AssessmentTestSessionTest.php
test/samples/custom/runtime/assessmenttest_context.xml

Ticket: https://oat-sa.atlassian.net/browse/TR-1432
Added a method that iterates through the rest of test items and closes test session.

Feature TR-1432 fast-forward to the last item and close the test session

---

qtism/runtime/tests/AssessmentTestSession.php

https://oat-sa.atlassian.net/browse/TR-2459
( deployed at http://test-tr-2459-timeouts.playground.kitchen.it.taocloud.org:49181/ )

fix: unify acceptable latency influence on mmove and jump behavior

---

src/qtism/common/ContentPackageExceptionInterface.php
src/qtism/common/QtiSdkPackageContentException.php
src/qtism/data/BranchRuleTargetException.php
src/qtism/data/results/DuplicateSourceIdException.php
src/qtism/data/storage/StorageException.php
src/qtism/data/storage/php/marshalling/PhpMarshallingException.php
src/qtism/data/storage/xml/marshalling/MarshallingException.php
src/qtism/runtime/pci/json/MarshallingException.php
src/qtism/runtime/rendering/RenderingException.php
src/qtism/runtime/storage/common/StorageException.php

https://oat-sa.atlassian.net/browse/TR-1265

fix: simplifies exceptions management

---

src/qtism/data/storage/xml/Utils.php
test/qtismtest/data/storage/xml/XmlUtilsTest.php

Removes the double encoding of attributes (see #324).

Release 17.0.1

---

qtism/runtime/pci/json/Unmarshaller.php
test/qtismtest/runtime/pci/json/JsonUnmarshallerTest.php

When unmarshalling RecordContainer list can be handle

fix: Record container handle list when unmarshalling

---

composer.json
src/qtism/common/storage/BinaryStreamAccess.php
src/qtism/common/storage/UnpackingStreamException.php

Release 19.0.2

---

src/qtism/common/storage/BinaryStreamAccess.php

release missed readInteger usage fix

Release 19.0.2 1

---

.github/workflows/release_tao_extension.yml

adding auto-semver release action

feat: added auto semver release for the repo

---

.github/workflows/continuous-integration.yaml
README.md

This PR addresses the issue where code coverage reports have not been pushed to the reports storage.

Fix code coverage reports

---

.github/workflows/continuous-integration.yaml
composer.json

increase php version to supported ones

fix: increase php version to supported ones
